#	$NetBSD:	$

.include <bsd.own.mk>

SUBDIR+=	executor
SUBDIR+=	hello
#SUBDIR+=	luahello		# Nothing to build here, only text files
SUBDIR+=	luareadhappy		# Needs an additional Lua script
SUBDIR+=	mapper			# Needs an additional helper program
SUBDIR+=	panic_string		# Crashes the system
SUBDIR+=	ping			# Needs an additional helper program
SUBDIR+=	properties
SUBDIR+=	readhappy
SUBDIR+=	readhappy_mpsafe	# Contains an additional helper program
SUBDIR+=	sysctl

.include <bsd.subdir.mk>
